from .Bloques import *
from .Mario import *
from .Monedas import *
from .Piso import *
from .Signos import *
from .Ladrillos import *
from .Tuberia import *
from .Escaleras import *
from .Goombas import *
from .Mastil import *